version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}-$(APPVEYOR_REPO_BRANCH)+$(APPVEYOR_REPO_COMMIT)'
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./TreeListView/TreeListView.csproj --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet pack ./TreeListView/TreeListView.csproj -c Release
after_build:
  # For once the build has completed
artifacts:
 - path: '\TreeListView\bin\Release\*.nupkg'
   name: NuGet Package
   type: NuGetPackage
clone_depth: 1
on_finish :
  # any cleanup in here
deploy: off